# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gregor Koenig
title: Passionate about technology used the right way for the right cause.
email: office@gkoenig.com
website: www.gkoenig.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: gregorkoenig
xing_username: Gregor_Koenig10
twitter_username: gkoenig
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a professional, self-motivated, and open-minded person with experience as engineering manager, software engineer, international project manager, and lecturer. I am passionate about technology and developing amazing solutions together with like-minded people. It is highly rewarding to support people in their professional journey and help them grown, thrive and prosper. 
  
  My technological focus lies on the research and development of secure communication and connectivity, (bio-)signal-processing, safety-critical embedded real-time systems, and their application in different fields. 
  
  I love science and I hold a PhD in Biomedical Engineering.

content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Barracuda Networks
        link: barracuda.com
        # link_text: boringcompany.com
        sub_title: Engineering Lead
        caption: 2013 - Present
        quote: >
          We build enterprise-grade, cloud-ready security solutions.

      - layout: left
        title: University of Applied Sciences Technikum Wien
        link: www.technikum-wien.at
        # link_text: boringcompany.com
        sub_title: Lecturer
        caption: 2014 - 2018

      - layout: left
        border: weak
        title: Austrian Institute of Technology
        link: ait.ac.at
        # link_text: boringcompany.com
        sub_title: Research Fellow, Postdoctoral Researcher
        caption: 2009 - 2012
        description: | # this will include new lines to allow paragraphs
             At the AIT I had the opportunity to work on my PhD research as a scientist in the field of bio-signal processing for medical devices. I also worked on other safety-critical aspects of medical products. During these four years I finished my PhD thesis at the Medical University of Vienna and was a lecturer at the Technical University of Vienna.

      - layout: left
        border: weak
        title: Frequentis AG
        link: frequentis.com
        # link_text: boringcompany.com
        sub_title: System Software Engineer
        caption: 2005 - 2008
        quote: >
          The leading global supplier of communication & information solutions for safety-critical applications.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Medical University of Vienna
        caption: 2009 - 2012
        sub_title: PhD Biomedical Engineering
        quote: >
          The Medical University of Vienna is the largest medical organisation in Austria, as well as one of the top-level research institutions in Europe and provides Europe's largest hospital, the Vienna General Hospital. There have been seven Nobel prize laureates affiliated with the medical faculty, and fifteen in total with the University of Vienna.
        description: | # this will include new lines to allow paragraphs
          During my time at Medical University if Vienna I did my PhD research in the field of bio-signal analysis (EEG, EOG, EMG) and the quantification of sleepiness and sleep quality. In 2012 I successfully finished my research and defended my [PhD thesis](https://www.amazon.de/EEG-based-Model-Daytime-Vigilance-Trends/dp/3838150848).

      - layout: left
        border: weak
        title: University of Salzburg
        caption: 2010 - 2013
        sub_title: MSc and BSc Computer Science

  - title: Philanthropic Activities
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: Feigenhain Initiative
        link: feigenhain.org
        caption: 2018 - Present
        sub_title: Founding Member
        description: | # this will include new lines to allow paragraphs
          The Feigenhain Initiative is a non-governmental non-profit organisation registered in France, with activities in Brazil, France and Austria. Our campaigns focus on humanitarian aid and cooperation, protection of the natural environment.

  - title: A Little More About Me
    layout: text
    border: weak
    content: | # this will include new lines to allow paragraphs
      Besides of my passion for technology my other interests and hobbies include
      - [Outdoor Sports](https://www.strava.com/athletes/mrgregor)
      - [Calisthenics](https://stevenlow.org/overcoming-gravity/)
      - [Running](https://www.schoenbrunn.at/)
      - [Cycling](https://www.zwift.com/eu/athlete/61ae74ef-85af-47df-ae48-9f0ef028e34b)
      - [Ilex paraguariensis](https://en.wikipedia.org/wiki/Yerba_mate)	
      
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
